using System;
using System.IO;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using CfAoiControl.Controllers;
using CfAoiControl.Models;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.PixelFormats;

namespace CfAoiControl.Services;

/// <summary>
/// Step 1 離線檢測：把影像送給 IP（offline-tcp），等 IP 寫出 {panel}_ResultInfo.json 後讀回。
/// （IP 收圖只回 OK，偵測結果寫到 IP --output；對齊 Verification step 3「讀 IP 產生的 JSON」。）
/// </summary>
public sealed class OfflineReviewService
{
    private readonly IpClient _ip;
    private readonly RecipeService _recipes;
    private readonly SystemConfigModel _cfg;
    private readonly LogService _log;
    private static readonly JsonSerializerOptions _json = new() { PropertyNameCaseInsensitive = true };

    public OfflineReviewService(IpClient ip, RecipeService recipes, SystemConfigModel cfg, LogService log)
    { _ip = ip; _recipes = recipes; _cfg = cfg; _log = log; }

    public sealed record AnalyzeOutcome(DefectResultModel Result, bool RecipeAutoGenerated);

    /// <summary>
    /// 送影像給 IP 分析。overrideZone 非 null 時，套用快速調參（BTH/DTH/Pitch）到配方第一個 ROI 後再送。
    /// </summary>
    public async Task<AnalyzeOutcome> AnalyzeImageAsync(
        string imagePath, string recipeName, int camId = 0,
        ZoneSettingModel? overrideZone = null, CancellationToken ct = default)
    {
        // 1) 確保配方存在（必要時自動生成）
        var ensure = await _recipes.EnsureRecipeExistsAsync(recipeName);
        var recipe = ensure.Recipe;

        // 1b) 套用快速調參覆寫到第一個 ROI
        if (overrideZone is not null && recipe.DetectRoiList.Count > 0)
        {
            var z = recipe.DetectRoiList[0];
            z.BrightThreshold = overrideZone.BrightThreshold;
            z.DarkThreshold = overrideZone.DarkThreshold;
            z.PitchX = overrideZone.PitchX;
            z.PitchY = overrideZone.PitchY;
            z.AlgorithmCompare = "DIV";
            await _recipes.SaveAsync(recipeName, recipe);   // 本機也存一份
        }

        // 2) 讀影像 → Mono8 raw bytes（ImageSharp，純 managed）
        var panel = Path.GetFileNameWithoutExtension(imagePath);
        using var img = Image.Load<L8>(imagePath);
        int w = img.Width, h = img.Height;
        var payload = new byte[(long)w * h];
        img.CopyPixelDataTo(payload);
        _log.Info($"送影像 {panel} ({w}×{h}) 給 IP @ {_ip.Host}:{_ip.Port}");

        // 3) 送 IP（network-clean，免共用檔案系統）：
        //    LOAD_RECIPE 帶配方 XML 內容 → STREAM_BEGIN → SEND_IMAGE_FOR_REVIEW（回應內含結果）
        var recipeXml = _recipes.ToXmlString(recipe);
        var lr = await _ip.LoadRecipeAsync(ensure.RecipeXmlPath, panel, recipeXml, ct);
        if (lr?["status"]?.GetValue<string>() != "OK")
            throw new InvalidOperationException($"IP LOAD_RECIPE 失敗：{lr?.ToJsonString()}");

        await _ip.SendImageStreamBeginAsync(panel, ct);
        var resp = await _ip.SendImageForReviewAsync(panel, camId, w, h, frameSeq: 0, payload, last: true, ct: ct);
        var status = resp?["status"]?.GetValue<string>();
        if (status != "OK")
            throw new InvalidOperationException($"IP 影像處理未回 OK：{resp?.ToJsonString()}");

        var resultNode = resp?["result"];
        if (resultNode is null)
            throw new InvalidOperationException("IP 回應缺少 result（請確認 IP 為 network-clean 版本）");
        var result = resultNode.Deserialize<DefectResultModel>(_json) ?? new DefectResultModel();

        _log.Info($"結果：{result.Summary}");
        return new AnalyzeOutcome(result, ensure.IsAutoGenerated);
    }

    /// <summary>
    /// 用「當前記憶體配方」(single source of truth) 直接送 IP，不經磁碟、不覆寫。
    /// 配方以 XML 內容 over TCP 送出（network-clean），回傳結果。
    /// </summary>
    public async Task<DefectResultModel> AnalyzeAsync(
        string imagePath, RecipeModel recipe, string recipeName, int camId = 0,
        bool saveDefectPatches = false, CancellationToken ct = default)
    {
        var panel = Path.GetFileNameWithoutExtension(imagePath);
        using var img = Image.Load<L8>(imagePath);
        int w = img.Width, h = img.Height;
        var payload = new byte[(long)w * h];
        img.CopyPixelDataTo(payload);
        _log.Info($"送影像 {panel} ({w}×{h}) 給 IP @ {_ip.Host}:{_ip.Port}");

        var recipeXml = _recipes.ToXmlString(recipe);
        var lr = await _ip.LoadRecipeAsync(recipeName, panel, recipeXml, ct);
        if (lr?["status"]?.GetValue<string>() != "OK")
            throw new InvalidOperationException($"IP LOAD_RECIPE 失敗：{lr?.ToJsonString()}");

        await _ip.SendImageStreamBeginAsync(panel, ct);
        var resp = await _ip.SendImageForReviewAsync(panel, camId, w, h, frameSeq: 0, payload,
                                                     last: true, debug: saveDefectPatches, ct: ct);
        if (resp?["status"]?.GetValue<string>() != "OK")
            throw new InvalidOperationException($"IP 影像處理未回 OK：{resp?.ToJsonString()}");
        var node = resp?["result"]
            ?? throw new InvalidOperationException("IP 回應缺少 result（請確認 IP 為 network-clean 版本）");
        var result = node.Deserialize<DefectResultModel>(_json) ?? new DefectResultModel();
        _log.Info($"結果：{result.Summary}");
        return result;
    }

    /// <summary>反序列化 IP 的 JSON（檔案版，供 selftest parse 用）。</summary>
    public static DefectResultModel ParseJson(string json) =>
        JsonSerializer.Deserialize<DefectResultModel>(json, _json) ?? new DefectResultModel();
}
