// ═══ 📖 手冊對照（docs/html/cf-aoi-training.html，開啟後 ⌘K 搜章節）═══
// [手冊 r4] F3 Step1 Test 端到端時序 / [手冊 p4] AnalyzeAsync 導師卡
// [手冊 ch2] network-clean（配方傳內容不傳路徑）
// ═══════════════════════════════════════════════════════════════
using System;
using System.IO;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using CfAoiControl.Controllers;
using CfAoiControl.Models;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.PixelFormats;

namespace CfAoiControl.Services;

/// <summary>
/// Step 1 離線檢測：把影像送給 IP（offline-tcp），等 IP 寫出 {panel}_ResultInfo.json 後讀回。
/// （IP 收圖只回 OK，偵測結果寫到 IP --output；對齊 Verification step 3「讀 IP 產生的 JSON」。）
/// </summary>
public sealed class OfflineReviewService
{
    private readonly IpClient _ip;
    private readonly RecipeService _recipes;
    private readonly SystemConfigModel _cfg;
    private readonly LogService _log;
    private static readonly JsonSerializerOptions _json = new() { PropertyNameCaseInsensitive = true };

    public OfflineReviewService(IpClient ip, RecipeService recipes, SystemConfigModel cfg, LogService log)
    { _ip = ip; _recipes = recipes; _cfg = cfg; _log = log; }

    public sealed record AnalyzeOutcome(DefectResultModel Result, bool RecipeAutoGenerated);

    /// <summary>
    /// 送影像給 IP 分析。overrideZone 非 null 時，套用快速調參（BTH/DTH/Pitch）到配方第一個 ROI 後再送。
    /// </summary>
    public async Task<AnalyzeOutcome> AnalyzeImageAsync(
        string imagePath, string recipeName, int camId = 0,
        ZoneSettingModel? overrideZone = null, CancellationToken ct = default)
    {
        // 1) 確保配方存在（必要時自動生成）
        var ensure = await _recipes.EnsureRecipeExistsAsync(recipeName);
        var recipe = ensure.Recipe;

        // 1b) 套用快速調參覆寫到第一個 ROI
        if (overrideZone is not null && recipe.DetectRoiList.Count > 0)
        {
            var z = recipe.DetectRoiList[0];
            z.BrightThreshold = overrideZone.BrightThreshold;
            z.DarkThreshold = overrideZone.DarkThreshold;
            z.PitchX = overrideZone.PitchX;
            z.PitchY = overrideZone.PitchY;
            z.AlgorithmCompare = "DIV";
            await _recipes.SaveAsync(recipeName, recipe);   // 本機也存一份
        }

        // 2) 讀影像 → Mono8 raw bytes（ImageSharp，純 managed）
        var panel = Path.GetFileNameWithoutExtension(imagePath);
        using var img = Image.Load<L8>(imagePath);
        int w = img.Width, h = img.Height;
        var payload = new byte[(long)w * h];
        img.CopyPixelDataTo(payload);
        _log.Info($"送影像 {panel} ({w}×{h}) 給 IP @ {_ip.Host}:{_ip.Port}");

        // 3) 送 IP（network-clean，免共用檔案系統）：
        //    LOAD_RECIPE 帶配方 XML 內容 → STREAM_BEGIN → SEND_IMAGE_FOR_REVIEW（回應內含結果）
        var recipeXml = _recipes.ToXmlString(recipe);
        // #16 Rule / #32 邊界略過 + 存圖設定：per-recipe RecipeSaving 經 recipe_saving 送 IP（缺檔→預設＝停用，不破 bit-exact）
        var saving = _recipes.LoadRecipeSetting(recipeName).BuildRecipeSavingJson();
        var lr = await _ip.LoadRecipeAsync(ensure.RecipeXmlPath, panel, recipeXml, recipeSaving: saving, ct: ct);
        if (lr?["status"]?.GetValue<string>() != "OK")
            throw new InvalidOperationException($"IP LOAD_RECIPE 失敗：{lr?.ToJsonString()}");

        await _ip.SendImageStreamBeginAsync(panel, ct);
        var resp = await _ip.SendImageForReviewAsync(panel, camId, w, h, frameSeq: 0, payload, last: true, ct: ct);
        var status = resp?["status"]?.GetValue<string>();
        if (status != "OK")
            throw new InvalidOperationException($"IP 影像處理未回 OK：{resp?.ToJsonString()}");

        var resultNode = resp?["result"];
        if (resultNode is null)
            throw new InvalidOperationException("IP 回應缺少 result（請確認 IP 為 network-clean 版本）");
        var result = resultNode.Deserialize<DefectResultModel>(_json) ?? new DefectResultModel();

        _log.Info($"結果：{result.Summary}");
        WarnEdgeCheck(result, panel);
        return new AnalyzeOutcome(result, ensure.IsAutoGenerated);
    }

    /// <summary>
    /// 用「當前記憶體配方」(single source of truth) 直接送 IP，不經磁碟、不覆寫。
    /// 配方以 XML 內容 over TCP 送出（network-clean），回傳結果。
    /// </summary>
    public async Task<DefectResultModel> AnalyzeAsync(
        string imagePath, RecipeModel recipe, string recipeName, int camId = 0,
        bool saveDefectPatches = false, CancellationToken ct = default)
    {
        var panel = Path.GetFileNameWithoutExtension(imagePath);
        using var img = Image.Load<L8>(imagePath);
        int w = img.Width, h = img.Height;
        var payload = new byte[(long)w * h];
        img.CopyPixelDataTo(payload);
        _log.Info($"送影像 {panel} ({w}×{h}) 給 IP @ {_ip.Host}:{_ip.Port}");

        var recipeXml = _recipes.ToXmlString(recipe);
        var saving = _recipes.LoadRecipeSetting(recipeName).BuildRecipeSavingJson();   // #16/#32 + 存圖設定
        var lr = await _ip.LoadRecipeAsync(recipeName, panel, recipeXml, recipeSaving: saving, ct: ct);
        if (lr?["status"]?.GetValue<string>() != "OK")
            throw new InvalidOperationException($"IP LOAD_RECIPE 失敗：{lr?.ToJsonString()}");

        await _ip.SendImageStreamBeginAsync(panel, ct);
        var resp = await _ip.SendImageForReviewAsync(panel, camId, w, h, frameSeq: 0, payload,
                                                     last: true, debug: saveDefectPatches, ct: ct);
        if (resp?["status"]?.GetValue<string>() != "OK")
            throw new InvalidOperationException($"IP 影像處理未回 OK：{resp?.ToJsonString()}");
        var node = resp?["result"]
            ?? throw new InvalidOperationException("IP 回應缺少 result（請確認 IP 為 network-clean 版本）");
        var result = node.Deserialize<DefectResultModel>(_json) ?? new DefectResultModel();
        _log.Info($"結果：{result.Summary}");
        WarnEdgeCheck(result, panel);
        return result;
    }

    /// <summary>
    /// 遠端影像：IP 讀「自己磁碟上的全解析度影像」跑檢測（與 SEND_IMAGE_FOR_REVIEW 同 process_image → bit-exact），
    /// 不搬全圖。先 LOAD_RECIPE（XML over TCP）再 REVIEW_LOCAL_IMAGE。回同一 DefectResultModel。
    /// </summary>
    public async Task<DefectResultModel> AnalyzeRemoteAsync(
        string remotePath, RecipeModel recipe, string recipeName,
        bool saveDefectPatches = false, CancellationToken ct = default)
    {
        var panel = Path.GetFileNameWithoutExtension(remotePath);
        var recipeXml = _recipes.ToXmlString(recipe);
        var saving = _recipes.LoadRecipeSetting(recipeName).BuildRecipeSavingJson();   // #16/#32 + 存圖設定
        var lr = await _ip.LoadRecipeAsync(recipeName, panel, recipeXml, recipeSaving: saving, ct: ct);
        if (lr?["status"]?.GetValue<string>() != "OK")
            throw new InvalidOperationException($"IP LOAD_RECIPE 失敗：{lr?.ToJsonString()}");
        _log.Info($"遠端檢測 {panel}（IP 磁碟全解析度）@ {_ip.Host}:{_ip.Port}");
        var resp = await _ip.ReviewLocalImageAsync(remotePath, panel, debug: saveDefectPatches, ct: ct);
        if (resp?["status"]?.GetValue<string>() != "OK")
            throw new InvalidOperationException($"IP REVIEW_LOCAL_IMAGE 未回 OK：{resp?.ToJsonString()}");
        var node = resp?["result"]
            ?? throw new InvalidOperationException("IP 回應缺少 result（請確認 IP 為支援 REVIEW_LOCAL_IMAGE 的版本）");
        var result = node.Deserialize<DefectResultModel>(_json) ?? new DefectResultModel();
        _log.Info($"遠端結果：{result.Summary}");
        WarnEdgeCheck(result, panel);
        return result;
    }

    /// <summary>
    /// 玻璃前緣/尾緣健檢警告路由：IP edge_check 欄位（停用時 null → 無感）→ 既有警告分頁。
    /// Align Fail = 進片 sensor→取像時序異常/前緣不在第一張；傳送異常 = 尾緣未見/速度漂移超閾值。
    /// </summary>
    private void WarnEdgeCheck(DefectResultModel result, string panel)
    {
        var e = result.EdgeCheck;
        if (e is null) return;
        if (!e.AlignOk)
            _log.Warn($"Align Fail：{panel} 玻璃前緣檢查失敗（{e.Summary}）— 檢查進片 sensor 觸發時序/傳送");
        if (!e.TransportOk)
            _log.Warn($"傳送異常：{panel} 玻璃尾緣/速度檢查失敗（{e.Summary}）— 檢查傳送片速度/取像張數");
        if (e.AlignOk && e.TransportOk)
            _log.Info($"EdgeCheck OK：{panel} {e.Summary}");
    }

    /// <summary>反序列化 IP 的 JSON（檔案版，供 selftest parse 用）。</summary>
    public static DefectResultModel ParseJson(string json) =>
        JsonSerializer.Deserialize<DefectResultModel>(json, _json) ?? new DefectResultModel();
}
