using System;
using System.IO;
using System.Threading.Tasks;
using System.Xml.Serialization;
using CfAoiControl.Models;

namespace CfAoiControl.Services;

public sealed record RecipeEnsureResult(RecipeModel Recipe, string RecipeXmlPath, bool IsAutoGenerated);

/// <summary>
/// 配方檔讀寫（沿用 legacy folder-per-recipe-per-IP：{RecipeDir}/{Recipe}/{Ip}/RecipeInfo.xml）。
/// 找不到 → 自動生成預設 DIV 配方（單一全幅 DetectRoi），標記 IsAutoGenerated（UI 顯示黃色警告）。
/// </summary>
public sealed class RecipeService
{
    private readonly SystemConfigModel _cfg;
    private readonly LogService _log;
    private static readonly XmlSerializer _ser = new(typeof(RecipeModel));
    private static readonly XmlSerializer _setSer = new(typeof(RecipeSavingModel));

    public RecipeService(SystemConfigModel cfg, LogService log) { _cfg = cfg; _log = log; }

    public string RecipeDirRoot => _cfg.Paths.RecipeDir;

    // 跨平台路徑展開：~（家目錄，Windows 亦適用 UserProfile）、~/a/b（拆段 Path.Combine）、
    // 絕對路徑（含 Windows C:\…）原樣回傳。確保 Mac/Linux/Windows 共用同一份設定。
    public static string ExpandPath(string p)
    {
        if (string.IsNullOrEmpty(p)) return p;
        var home = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);
        if (p == "~") return home;
        if (p.StartsWith("~/") || p.StartsWith("~\\"))
        {
            var combined = home;
            foreach (var seg in p[2..].Replace('\\', '/').Split('/', StringSplitOptions.RemoveEmptyEntries))
                combined = Path.Combine(combined, seg);
            return combined;
        }
        return p;   // 絕對路徑原樣（Windows C:\… / *nix /…）
    }

    public string RecipeXmlPath(string recipeName, string ipName = "IP0") =>
        Path.Combine(ExpandPath(_cfg.Paths.RecipeDir), recipeName, ipName, "RecipeInfo.xml");

    public RecipeModel Load(string xmlPath)
    {
        using var fs = File.OpenRead(xmlPath);
        return (RecipeModel)(_ser.Deserialize(fs) ?? new RecipeModel());
    }

    /// <summary>序列化為 XML 字串（跨機器：經 TCP 把配方內容送給 IP）。</summary>
    public string ToXmlString(RecipeModel recipe)
    {
        using var sw = new StringWriter();
        var ns = new XmlSerializerNamespaces();
        ns.Add("", "");
        _ser.Serialize(sw, recipe, ns);
        return sw.ToString();
    }

    public void Save(string recipeName, RecipeModel recipe, string ipName = "IP0")
    {
        var path = RecipeXmlPath(recipeName, ipName);
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        using var fs = File.Create(path);
        var ns = new XmlSerializerNamespaces();
        ns.Add("", "");                 // 不寫 namespace，貼近 legacy 輸出
        _ser.Serialize(fs, recipe, ns);
        _log.Info($"配方已存：{path}");
    }

    public Task SaveAsync(string recipeName, RecipeModel recipe, string ipName = "IP0")
    { Save(recipeName, recipe, ipName); return Task.CompletedTask; }

    // ---- RecipeSetting（per-recipe 存圖設定，= legacy RecipeSetting.xml，放配方資料夾根）----
    public string RecipeSettingXmlPath(string recipeName) =>
        Path.Combine(ExpandPath(_cfg.Paths.RecipeDir), recipeName, "RecipeSetting.xml");

    /// <summary>讀 per-recipe RecipeSetting.xml；不存在則回預設（並帶入 RecipeName）。</summary>
    public RecipeSavingModel LoadRecipeSetting(string recipeName)
    {
        var path = RecipeSettingXmlPath(recipeName);
        if (File.Exists(path))
        {
            try
            {
                using var fs = File.OpenRead(path);
                var m = (RecipeSavingModel)(_setSer.Deserialize(fs) ?? new RecipeSavingModel());
                if (string.IsNullOrEmpty(m.RecipeName)) m.RecipeName = recipeName;
                return m;
            }
            catch (Exception ex) { _log.Error($"讀 RecipeSetting 失敗（{path}）：{ex.Message}"); }
        }
        return new RecipeSavingModel { RecipeName = recipeName };
    }

    public void SaveRecipeSetting(string recipeName, RecipeSavingModel model)
    {
        model.RecipeName = recipeName;
        var path = RecipeSettingXmlPath(recipeName);
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        using var fs = File.Create(path);
        var ns = new XmlSerializerNamespaces();
        ns.Add("", "");
        _setSer.Serialize(fs, model, ns);
        _log.Info($"RecipeSetting 已存：{path}");
    }

    public RecipeEnsureResult EnsureRecipeExists(string recipeName, string ipName = "IP0")
    {
        var path = RecipeXmlPath(recipeName, ipName);
        if (File.Exists(path))
            return new RecipeEnsureResult(Load(path), path, IsAutoGenerated: false);

        // 自動生成預設 DIV 配方（單一全幅 zone）
        var recipe = new RecipeModel();
        recipe.DetectRoiList.Add(new ZoneSettingModel
        {
            StartX = -1, StartY = -1, EndX = -1, EndY = -1,   // 全幅
            AlgorithmWay = "8-Way-Star", AlgorithmCompare = "DIV",
            BrightThreshold = 1.4, DarkThreshold = 0.6,
            PitchX = 26, PitchY = 19, SearchX = 1, SearchY = 1,
        });
        Save(recipeName, recipe, ipName);
        _log.Warn($"配方 '{recipeName}' 不存在 → 已自動生成預設 DIV 配方，請確認 PitchX/PitchY！");
        return new RecipeEnsureResult(recipe, path, IsAutoGenerated: true);
    }

    public Task<RecipeEnsureResult> EnsureRecipeExistsAsync(string recipeName, string ipName = "IP0")
        => Task.FromResult(EnsureRecipeExists(recipeName, ipName));
}
