using System;
using System.IO;
using System.Threading.Tasks;
using System.Xml.Serialization;
using CfAoiControl.Models;

namespace CfAoiControl.Services;

public sealed record RecipeEnsureResult(RecipeModel Recipe, string RecipeXmlPath, bool IsAutoGenerated);

/// <summary>
/// 配方檔讀寫（沿用 legacy folder-per-recipe-per-IP：{RecipeDir}/{Recipe}/{Ip}/RecipeInfo.xml）。
/// 找不到 → 自動生成預設 DIV 配方（單一全幅 DetectRoi），標記 IsAutoGenerated（UI 顯示黃色警告）。
/// </summary>
public sealed class RecipeService
{
    private readonly SystemConfigModel _cfg;
    private readonly LogService _log;
    private static readonly XmlSerializer _ser = new(typeof(RecipeModel));

    public RecipeService(SystemConfigModel cfg, LogService log) { _cfg = cfg; _log = log; }

    public static string ExpandPath(string p) =>
        p.StartsWith("~/") || p == "~"
            ? Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), p.Length > 1 ? p[2..] : "")
            : p;

    public string RecipeXmlPath(string recipeName, string ipName = "IP0") =>
        Path.Combine(ExpandPath(_cfg.Paths.RecipeDir), recipeName, ipName, "RecipeInfo.xml");

    public RecipeModel Load(string xmlPath)
    {
        using var fs = File.OpenRead(xmlPath);
        return (RecipeModel)(_ser.Deserialize(fs) ?? new RecipeModel());
    }

    /// <summary>序列化為 XML 字串（跨機器：經 TCP 把配方內容送給 IP）。</summary>
    public string ToXmlString(RecipeModel recipe)
    {
        using var sw = new StringWriter();
        var ns = new XmlSerializerNamespaces();
        ns.Add("", "");
        _ser.Serialize(sw, recipe, ns);
        return sw.ToString();
    }

    public async Task SaveAsync(string recipeName, RecipeModel recipe, string ipName = "IP0")
    {
        var path = RecipeXmlPath(recipeName, ipName);
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        await using var fs = File.Create(path);
        // 不寫 namespace，貼近 legacy 輸出
        var ns = new XmlSerializerNamespaces();
        ns.Add("", "");
        _ser.Serialize(fs, recipe, ns);
        _log.Info($"配方已存：{path}");
    }

    public async Task<RecipeEnsureResult> EnsureRecipeExistsAsync(string recipeName, string ipName = "IP0")
    {
        var path = RecipeXmlPath(recipeName, ipName);
        if (File.Exists(path))
            return new RecipeEnsureResult(Load(path), path, IsAutoGenerated: false);

        // 自動生成預設 DIV 配方（單一全幅 zone）
        var recipe = new RecipeModel();
        recipe.DetectRoiList.Add(new ZoneSettingModel
        {
            StartX = -1, StartY = -1, EndX = -1, EndY = -1,   // 全幅
            AlgorithmWay = "8-Way-Star", AlgorithmCompare = "DIV",
            BrightThreshold = 1.4, DarkThreshold = 0.6,
            PitchX = 26, PitchY = 19, SearchX = 1, SearchY = 1,
        });
        await SaveAsync(recipeName, recipe, ipName);
        _log.Warn($"配方 '{recipeName}' 不存在 → 已自動生成預設 DIV 配方，請確認 PitchX/PitchY！");
        return new RecipeEnsureResult(recipe, path, IsAutoGenerated: true);
    }
}
