using System;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Avalonia.Media.Imaging;
using CfAoiControl.Models;
using CfAoiControl.Services;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.PixelFormats;
using SixLabors.ImageSharp.Processing;

namespace CfAoiControl.ViewModels;

public partial class Step1ViewModel : ViewModelBase
{
    private readonly AppServices _svc;
    private const int PatchSize = 100;

    public Step1ViewModel(AppServices svc)
    {
        _svc = svc;
        SelectedImagePath = DefaultImagePath();
        RefreshRecipeNames();
    }

    // 影像 / 配方
    [ObservableProperty] private string selectedImagePath = "";
    [ObservableProperty] private string selectedRecipe = "DEFAULT";
    public ObservableCollection<string> RecipeNames { get; } = new();

    // 快速調參（對齊 IP：BrightThreshold→BTH, DarkThreshold→DTH；非 ThB/ThD）
    [ObservableProperty] private double brightThreshold = 1.4;
    [ObservableProperty] private double darkThreshold = 0.6;
    [ObservableProperty] private int pitchX = 26;
    [ObservableProperty] private int pitchY = 19;

    // 狀態 / 結果
    [ObservableProperty] private bool isAnalyzing;
    [ObservableProperty] private string statusMessage = "就緒";
    [ObservableProperty] private bool showAutoGenWarning;
    [ObservableProperty] private string resultSummary = "";
    [ObservableProperty] private DefectModel? selectedDefect;
    [ObservableProperty] private Bitmap? selectedDefectBitmap;

    public ObservableCollection<DefectModel> Defects { get; } = new();

    // 由 View code-behind 設定（用 StorageProvider 選檔）；headless 時為 null
    public Func<Task<string?>>? FilePicker { get; set; }

    [RelayCommand]
    private async Task BrowseImage()
    {
        if (FilePicker is null) return;
        var p = await FilePicker();
        if (!string.IsNullOrEmpty(p)) SelectedImagePath = p!;
    }

    private bool CanRun() => !IsAnalyzing && File.Exists(SelectedImagePath);

    [RelayCommand(CanExecute = nameof(CanRun))]
    private async Task RunAnalysis()
    {
        IsAnalyzing = true;
        StatusMessage = "傳送影像中…";
        try
        {
            var overrideZone = new ZoneSettingModel
            {
                BrightThreshold = BrightThreshold, DarkThreshold = DarkThreshold,
                PitchX = PitchX, PitchY = PitchY, AlgorithmCompare = "DIV",
            };
            var outcome = await _svc.Review.AnalyzeImageAsync(SelectedImagePath, SelectedRecipe, 0, overrideZone);
            ShowAutoGenWarning = outcome.RecipeAutoGenerated;

            Defects.Clear();
            foreach (var d in outcome.Result.AllDefects) Defects.Add(d);
            ResultSummary = outcome.Result.Summary;
            StatusMessage = $"完成：{outcome.Result.DefectCnt} 個缺陷";
        }
        catch (Exception ex) { StatusMessage = $"❌ {ex.Message}"; }
        finally { IsAnalyzing = false; }
    }

    [RelayCommand] private void SaveRecipe() => _ = SaveRecipeAsync();
    private async Task SaveRecipeAsync()
    {
        var ensure = await _svc.Recipes.EnsureRecipeExistsAsync(SelectedRecipe);
        var z = ensure.Recipe.DetectRoiList.FirstOrDefault() ?? new ZoneSettingModel();
        if (ensure.Recipe.DetectRoiList.Count == 0) ensure.Recipe.DetectRoiList.Add(z);
        z.BrightThreshold = BrightThreshold; z.DarkThreshold = DarkThreshold;
        z.PitchX = PitchX; z.PitchY = PitchY; z.AlgorithmCompare = "DIV";
        await _svc.Recipes.SaveAsync(SelectedRecipe, ensure.Recipe);
        StatusMessage = "配方已儲存";
    }

    // A5 #1：缺陷 OK/NG 一鍵歸檔（AI 訓練資料）
    [RelayCommand] private void ClassifyOk() => FileSelectedDefect("ok");
    [RelayCommand] private void ClassifyNg() => FileSelectedDefect("ng");

    private void FileSelectedDefect(string klass)
    {
        if (SelectedDefect is null || !File.Exists(SelectedImagePath)) return;
        try
        {
            var dir = Path.Combine(RecipeService.ExpandPath(_svc.Config.Paths.OutputDir), klass);
            Directory.CreateDirectory(dir);
            using var patch = CropPatch(SelectedImagePath, SelectedDefect);
            var name = $"{Path.GetFileNameWithoutExtension(SelectedImagePath)}_{SelectedDefect.GlobalPosX}_{SelectedDefect.GlobalPosY}_{SelectedDefect.Type}.png";
            patch.SaveAsPng(Path.Combine(dir, name));
            StatusMessage = $"已歸檔 {klass.ToUpper()}：{name}";
        }
        catch (Exception ex) { StatusMessage = $"❌ 歸檔失敗：{ex.Message}"; }
    }

    partial void OnSelectedDefectChanged(DefectModel? value)
    {
        SelectedDefectBitmap?.Dispose();
        SelectedDefectBitmap = null;
        if (value is null || !File.Exists(SelectedImagePath)) return;
        try
        {
            using var patch = CropPatch(SelectedImagePath, value);
            using var ms = new MemoryStream();
            patch.SaveAsPng(ms);
            ms.Position = 0;
            SelectedDefectBitmap = new Bitmap(ms);
        }
        catch { /* 顯示失敗不致命 */ }
    }

    // 由原始影像裁切 PatchSize×PatchSize（以缺陷全域座標為中心）
    private static Image<L8> CropPatch(string imagePath, DefectModel d)
    {
        var img = Image.Load<L8>(imagePath);
        int half = PatchSize / 2;
        int x = Math.Clamp(d.GlobalPosX - half, 0, Math.Max(0, img.Width - PatchSize));
        int y = Math.Clamp(d.GlobalPosY - half, 0, Math.Max(0, img.Height - PatchSize));
        int w = Math.Min(PatchSize, img.Width - x);
        int h = Math.Min(PatchSize, img.Height - y);
        img.Mutate(c => c.Crop(new Rectangle(x, y, w, h)));
        return img;
    }

    private void RefreshRecipeNames()
    {
        RecipeNames.Clear();
        RecipeNames.Add("DEFAULT");
        try
        {
            var root = RecipeService.ExpandPath(_svc.Config.Paths.RecipeDir);
            if (Directory.Exists(root))
                foreach (var d in Directory.GetDirectories(root))
                {
                    var n = Path.GetFileName(d);
                    if (!RecipeNames.Contains(n)) RecipeNames.Add(n);
                }
        }
        catch { }
        if (!RecipeNames.Contains(SelectedRecipe)) SelectedRecipe = "DEFAULT";
    }

    private string DefaultImagePath()
    {
        try
        {
            var dir = RecipeService.ExpandPath(_svc.Config.Paths.ImageDir);
            if (Directory.Exists(dir))
            {
                var first = Directory.EnumerateFiles(dir)
                    .FirstOrDefault(f => f.EndsWith(".tif", StringComparison.OrdinalIgnoreCase)
                                      || f.EndsWith(".png", StringComparison.OrdinalIgnoreCase)
                                      || f.EndsWith(".bmp", StringComparison.OrdinalIgnoreCase));
                if (first != null) return first;
            }
        }
        catch { }
        return "";
    }
}
